### ISSUE TITLE
缺少admin/main.html

### ISSUE THREAD

**Issue by Develkone** [lightTrace/beego-blog#2]
源文件里缺少了main.html导致登陆后跳转失败

**Comment by lightTrace** [comment]
c.History("登录成功", "/admin/main.html") 这一行代码指定的main.html不一定就是去寻找main.html,可以解析所有以main开头的文件，所以会找到main.tpl文件

**Comment by Develkone** [comment]
> c.History("登录成功", "/admin/main.html") 这一行代码指定的main.html不一定就是去寻找main.html,可以解析所有以main开头的文件，所以会找到main.tpl文件

多谢指点
